### ISSUE TITLE
Publish error

### ISSUE THREAD

**Issue by maasencioh** [cheminfo/tools#129]
When I try to publish a package I get the following error `[TypeError: adminInfo[org].includes is not a function]`.

I tried the following entries:
- `cheminfo publish`
- `cheminfo publish -o ml`
- `cheminfo publish -o ml -b major`

**Comment by targos** [comment]
You probably have an old version of node that doesn't have the includes method

**Comment by maasencioh** [comment]
It's the v4.4.4, but I think that it's the LTS, so it's not a bad idea to have it working
