### ISSUE TITLE
Automatic update

### ISSUE THREAD

**Issue by maasencioh** [cheminfo/tools#167]
When the version is obsolete should ask to the user to update, and if the answer is yes should update, if not continue with his current task

**Comment by maasencioh** [comment]
@targos @lpatiny what do you think of this behaviour?

**Comment by targos** [comment]
generally +1 for auto-update but I don't like the idea to continue the task. I intentionnally stopped the task so that you have to explicitly pass `--force` to run an obsolete version

**Comment by stropitek** [comment]
@maasencioh can you comment on why you closed this?

**Comment by targos** [comment]
we decided it's not worth the effort vs. letting the user copy-paste the update command
