### ISSUE TITLE
tab autocompletion

### ISSUE THREAD

**Issue by maasencioh** [cheminfo/tools#169]
Consider using https://github.com/mklabs/node-tabtab

**Comment by tsriram** [comment]
Shall I take this up?

**Comment by maasencioh** [comment]
Hello @tsriram, thanks for the interest, all the PR are more than welcomed!

**Comment by tsriram** [comment]
@maasencioh I've created a WIP PR #170 for this issue. Have taken 4 commands from bin/cheminfo.js and passed them as tab complete options for cheminfo. Take a look at it and let me know if this is okay.
