### ISSUE TITLE
Why are we publishing dist on master

### ISSUE THREAD

**Issue by stropitek** [cheminfo/tools#207]
I don't remember why `grm` publishes the built directory `dist` to github master branch. I find it annoying not to git ignore this directory. And some users blindly commit this directory everytime they change it locally.

Is there an easy alternative?

**Comment by stropitek** [comment]
Is it for bower?

**Comment by targos** [comment]
it is for bower

**Comment by targos** [comment]
We could make it opt-in. most of the libraries that we develop now don't need to be on bower

**Comment by stropitek** [comment]
Ok that would be nice to have

**Comment by stropitek** [comment]
The issue belongs to GRM right?

**Comment by targos** [comment]
That islamo-nationalistes correct

**Comment by targos** [comment]
Hahaha this autocorrect is so bad

**Comment by stropitek** [comment]
Hahaha this is hilarious!!! But I could still understand what you meant to say

**Comment by stropitek** [comment]
https://github.com/cheminfo/grm/issues/15

**Comment by maasencioh** [comment]
Best issue ever jajajajajaja

![islamo-nationalistes](http://i.imgur.com/FqThhQs.jpg)
