### ISSUE TITLE
error when trying to generate 

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/tools#215]
I have isntall the tools using `npm install -g cheminfo-tools`but when trying to generate a new project I guet an error

➜  cheminfo generate                
{ Error: Cannot find module 'generator-cheminfo'
    at Function.Module._resolveFilename (module.js:485:15)

**Comment by lpatiny** [comment]
@maasencioh  Any idea ?

**Comment by maasencioh** [comment]
I'm checking it out

**Comment by targos** [comment]
`cheminfo generate` has been removed. `yo cheminfo:TYPE` should be used directly instead.
