### ISSUE TITLE
Link is wrong

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/tools#226]
I received the following error:

```
Adding to organization
Could not add the package to npm organization.
Please go to npm team config (​https://www.npmjs.com/settings/cheminfo/teams/team/developers/access​) and add openchemlib-utils to the team.
Pushing to GitHub
```

But the link does not work

**Comment by targos** [comment]
It works for me, and it should work for you too (you're an admin). What do you see at this page?

**Comment by lpatiny** [comment]
Strange

![image](https://user-images.githubusercontent.com/1484241/72797793-18373200-3c42-11ea-85c3-5ff942d510eb.png)

**Comment by targos** [comment]
And it says "Route not found", so it's not about permissions.
Maybe there is some special character from the terminal in the URL?

**Comment by lpatiny** [comment]
Thanks indeed when you click in the terminal on the link there are some extra character at the end and removing them works

![image](https://user-images.githubusercontent.com/1484241/72801743-76681300-3c4a-11ea-9f70-287ab4ceefac.png)
