### ISSUE TITLE
add prefix to generated files

### ISSUE THREAD

**Issue by targos** [cheminfo/tools#4]
Like we had before:

```
/**
 * jcampconverter - Parse and convert JCAMP data
 * @version v2.1.0
 * @link https://github.com/cheminfo/jcampconverter
 * @license MIT
 */

// jcampconverter@v2.1.0, MIT licensed. https://github.com/cheminfo/jcampconverter
```

**Comment by maasencioh** [comment]
Hi, where it's this header added and it's based in what?

**Comment by targos** [comment]
It is for the `cheminfo build` command.
The headers should be added at the beginning of the built files (first header for normal build, second for minified build)
Information comes from the package.json:
- jcampconverter: pkg.name
- Parse and ... : pkg.description
- etc

**Comment by targos** [comment]
We can probably use webpack's banner plugin: https://webpack.js.org/plugins/banner-plugin/
